name: application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map.png
    - assets/image-1.png
    - assets/image-2.png
    - assets/youtube-1.png
    - assets/youtube-2.png
    - assets/youtube-3.png
    - assets/logo-1.png
    - assets/penny-jar.png
    - assets/story-1.png
    - assets/story-2.png
    - assets/story-3.png
    - assets/story-4.png
    - assets/story-5.png
    - assets/story-6.png
    - assets/instagram-1.png
    - assets/instagram-2.png
    - assets/topd-1.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800